[package]
name = "vga"
version = "0.1.0"
authors = ["k0pernicus <antonin.carette@gmail.com>"]

[dependencies]
spin = "0.4.6"
volatile = "0.1.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
